#!/usr/bin/env bash
# tests/test_pr_signature.sh — Octopus signature convention on PR-posting surfaces.
#
# Rule: a *general PR comment* (or PR body) is signed with the Octopus footer;
# *inline thread replies* are not. Locks the distinction so a future edit can't
# silently start signing per-thread replies or drop the footer from general posts.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIG='<sub>🐙 generated by Octopus</sub>'
PASS=0; FAIL=0

signs()      { grep -qF "$SIG" "$1"; }
must_sign()  { if signs "$ROOT/$1"; then echo "PASS: $2"; PASS=$((PASS+1)); else echo "FAIL: $2"; FAIL=$((FAIL+1)); fi; }
must_not()   { if signs "$ROOT/$1"; then echo "FAIL: $2"; FAIL=$((FAIL+1)); else echo "PASS: $2"; PASS=$((PASS+1)); fi; }

echo "=== PR signature convention ==="
# General posts (PR body / aggregated report comment) → signed.
must_sign "commands/pr-open.md"    "pr-open signs the PR body"
must_sign "commands/pr-review.md"  "pr-review signs the aggregated report (general comment)"
# Inline thread replies → not signed (would clutter the thread).
must_not  "commands/pr-comments.md"          "pr-comments does NOT sign inline thread replies"
must_not  "skills/respond-to-review/SKILL.md" "respond-to-review does NOT sign inline thread replies"

echo "--------------------------------------------------"
echo "PASS=$PASS FAIL=$FAIL"
[[ $FAIL -eq 0 ]]
