#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/setup.sh" --source-only

TMPDIR=$(mktemp -d)
PROJECT_ROOT="$TMPDIR"
OCTOPUS_DIR="$SCRIPT_DIR"

reset_state() {
  rm -rf "$TMPDIR/knowledge" "$TMPDIR/.claude" "$TMPDIR/.github"
  OCTOPUS_KNOWLEDGE_ENABLED="false"
  OCTOPUS_KNOWLEDGE_MODE=""
  OCTOPUS_KNOWLEDGE_DIR="knowledge"
  OCTOPUS_KNOWLEDGE_LIST=()
  OCTOPUS_KNOWLEDGE_ROLES=()
  KNOWLEDGE_MODULES=()
  OCTOPUS_ROLES=()
  OCTOPUS_CONTEXT=""
  _ROLES_CONTEXT_LOADED=""
  MANIFEST_CAP_KNOWLEDGE="false"
  MANIFEST_DELIVERY_KNOWLEDGE_METHOD=""
  MANIFEST_DELIVERY_KNOWLEDGE_TARGET=""
}

# Helper: create a knowledge module with N markdown files
make_module() {
  local mod="$1"
  local n_files="${2:-1}"
  mkdir -p "$TMPDIR/knowledge/$mod"
  for i in $(seq 1 "$n_files"); do
    echo "# ${mod} file ${i}" > "$TMPDIR/knowledge/$mod/file${i}.md"
  done
}

# --- Test 1: Auto-discover skips _prefixed dirs ---
echo "Test 1: Auto-discover"
reset_state
make_module domain
make_module auth
mkdir -p "$TMPDIR/knowledge/_template"
OCTOPUS_KNOWLEDGE_ENABLED="true"
OCTOPUS_KNOWLEDGE_MODE="auto"

discover_knowledge

[[ ${#KNOWLEDGE_MODULES[@]} -eq 2 ]] || { echo "FAIL: expected 2 modules, got ${#KNOWLEDGE_MODULES[@]}"; exit 1; }
[[ " ${KNOWLEDGE_MODULES[*]} " == *" domain "* ]] || { echo "FAIL: domain not discovered"; exit 1; }
[[ " ${KNOWLEDGE_MODULES[*]} " == *" auth "* ]] || { echo "FAIL: auth not discovered"; exit 1; }
[[ " ${KNOWLEDGE_MODULES[*]} " != *" _template "* ]] || { echo "FAIL: _template should be skipped"; exit 1; }
echo "PASS: Auto-discover"

# --- Test 2: Explicit list only includes listed modules ---
echo "Test 2: Explicit list"
reset_state
make_module domain
make_module auth
OCTOPUS_KNOWLEDGE_ENABLED="true"
OCTOPUS_KNOWLEDGE_MODE="explicit"
OCTOPUS_KNOWLEDGE_LIST=(domain)

discover_knowledge

[[ ${#KNOWLEDGE_MODULES[@]} -eq 1 ]] || { echo "FAIL: expected 1 module, got ${#KNOWLEDGE_MODULES[@]}"; exit 1; }
[[ "${KNOWLEDGE_MODULES[0]}" == "domain" ]] || { echo "FAIL: expected domain, got ${KNOWLEDGE_MODULES[0]}"; exit 1; }
echo "PASS: Explicit list"

# --- Test 3: Missing module warning ---
echo "Test 3: Missing module warning"
reset_state
make_module domain
OCTOPUS_KNOWLEDGE_ENABLED="true"
OCTOPUS_KNOWLEDGE_MODE="explicit"
OCTOPUS_KNOWLEDGE_LIST=(domain nonexistent)

_warn_out=$(mktemp)
discover_knowledge > "$_warn_out" 2>&1

[[ ${#KNOWLEDGE_MODULES[@]} -eq 1 ]] || { echo "FAIL: expected 1 module after skipping missing, got ${#KNOWLEDGE_MODULES[@]}"; exit 1; }
[[ "${KNOWLEDGE_MODULES[0]}" == "domain" ]] || { echo "FAIL: domain should still be discovered"; exit 1; }
grep -qi "warning" "$_warn_out" || { echo "FAIL: should warn about missing module"; exit 1; }
rm -f "$_warn_out"
echo "PASS: Missing module warning"

# --- Test 4: INDEX.md generation ---
echo "Test 4: INDEX.md generation"
reset_state
make_module domain 3
make_module auth 2
KNOWLEDGE_MODULES=(domain auth)

generate_knowledge_index

[[ -f "$TMPDIR/knowledge/INDEX.md" ]] || { echo "FAIL: INDEX.md not created"; exit 1; }
grep -q "domain" "$TMPDIR/knowledge/INDEX.md" || { echo "FAIL: domain not in INDEX.md"; exit 1; }
grep -q "auth" "$TMPDIR/knowledge/INDEX.md" || { echo "FAIL: auth not in INDEX.md"; exit 1; }
grep -q "3" "$TMPDIR/knowledge/INDEX.md" || { echo "FAIL: file count 3 not in INDEX.md"; exit 1; }
grep -q "2" "$TMPDIR/knowledge/INDEX.md" || { echo "FAIL: file count 2 not in INDEX.md"; exit 1; }
grep -q "Auto-generated by Octopus" "$TMPDIR/knowledge/INDEX.md" || { echo "FAIL: auto-generated header missing"; exit 1; }
echo "PASS: INDEX.md generation"

# --- Test 5: Role assembly without mapping (all modules) ---
echo "Test 5: Role assembly without mapping"
reset_state
make_module domain
echo "Domain fact" > "$TMPDIR/knowledge/domain/knowledge.md"
make_module auth
echo "Auth fact" > "$TMPDIR/knowledge/auth/knowledge.md"
KNOWLEDGE_MODULES=(domain auth)

content=$(assemble_knowledge "")

echo "$content" | grep -q "Domain fact" || { echo "FAIL: domain content missing"; exit 1; }
echo "$content" | grep -q "Auth fact" || { echo "FAIL: auth content missing"; exit 1; }
echo "PASS: Role assembly without mapping"

# --- Test 6: Role assembly with role mapping ---
echo "Test 6: Role assembly with role mapping"
reset_state
make_module domain
echo "Domain fact" > "$TMPDIR/knowledge/domain/knowledge.md"
make_module auth
echo "Auth fact" > "$TMPDIR/knowledge/auth/knowledge.md"
make_module payments
echo "Payments fact" > "$TMPDIR/knowledge/payments/knowledge.md"
KNOWLEDGE_MODULES=(domain auth payments)
OCTOPUS_KNOWLEDGE_ROLES[backend-specialist]="domain,auth"
OCTOPUS_KNOWLEDGE_ROLES[product-manager]="domain"

backend_content=$(assemble_knowledge "backend-specialist")
pm_content=$(assemble_knowledge "product-manager")

echo "$backend_content" | grep -q "Domain fact" || { echo "FAIL: backend missing domain"; exit 1; }
echo "$backend_content" | grep -q "Auth fact" || { echo "FAIL: backend missing auth"; exit 1; }
echo "$backend_content" | grep -qi "Payments fact" && { echo "FAIL: backend should not have payments"; exit 1; }
echo "$pm_content" | grep -q "Domain fact" || { echo "FAIL: PM missing domain"; exit 1; }
echo "$pm_content" | grep -qi "Auth fact" && { echo "FAIL: PM should not have auth"; exit 1; }
echo "PASS: Role assembly with role mapping"

# --- Test 7: Backward compat — no knowledge config uses .octopus-context.md ---
echo "Test 7: Backward compatibility"
reset_state
cat > "$TMPDIR/.octopus-context.md" << 'EOF'
# Legacy Context
Legacy project context here.
EOF

# KNOWLEDGE_MODULES is empty (no knowledge: config)
OCTOPUS_ROLES=(product-manager)
OCTOPUS_AGENTS=(claude)
declare -A OCTOPUS_AGENT_OUTPUT=()
load_manifest "claude"

deliver_roles "claude"

grep -q "Legacy project context here" "$TMPDIR/.claude/agents/product-manager.md" || \
  { echo "FAIL: legacy context not injected when no knowledge modules"; exit 1; }
echo "PASS: Backward compatibility"

# --- Test 8: Coexistence — .octopus-context.md prepended before knowledge ---
echo "Test 8: Coexistence of context file and knowledge modules"
reset_state
cat > "$TMPDIR/.octopus-context.md" << 'EOF'
# Legacy Context
Legacy project context here.
EOF
make_module domain
echo "Domain knowledge here." > "$TMPDIR/knowledge/domain/knowledge.md"
KNOWLEDGE_MODULES=(domain)
OCTOPUS_ROLES=(product-manager)
OCTOPUS_AGENTS=(claude)
declare -A OCTOPUS_AGENT_OUTPUT=()
load_manifest "claude"

deliver_roles "claude"

grep -q "Legacy project context here" "$TMPDIR/.claude/agents/product-manager.md" || \
  { echo "FAIL: legacy context not present when knowledge modules active"; exit 1; }
grep -q "Domain knowledge here" "$TMPDIR/.claude/agents/product-manager.md" || \
  { echo "FAIL: knowledge module content not present"; exit 1; }
echo "PASS: Coexistence"

# --- Test 9: Claude symlink delivery ---
echo "Test 9: Claude symlink delivery"
reset_state
make_module domain
KNOWLEDGE_MODULES=(domain)
MANIFEST_CAP_KNOWLEDGE="true"
MANIFEST_DELIVERY_KNOWLEDGE_METHOD="symlink"
MANIFEST_DELIVERY_KNOWLEDGE_TARGET=".claude/knowledge/"

deliver_knowledge "claude"

symlink_path="${TMPDIR}/.claude/knowledge"
[[ -L "$symlink_path" ]] || { echo "FAIL: .claude/knowledge symlink not created"; exit 1; }
sym_target=$(readlink "$symlink_path")
[[ "$sym_target" == "$TMPDIR/knowledge" ]] || { echo "FAIL: symlink points to wrong target: $sym_target"; exit 1; }
echo "PASS: Claude symlink delivery"

rm -rf "$TMPDIR"
echo "PASS: all knowledge tests passed"
