#!/usr/bin/env bash
# RM-088 — Stop hook that, at task end, detects an uncommitted working diff
# and queues a grounding review: it writes a proposal to
# .octopus/proposals/<timestamp>-grounding.md asking for an `audit-grounding`
# run against the diff, to surface invented conventions and unsupported
# domain facts vs. the source of truth (CONTEXT.md, docs/adr/, knowledge/).
#
# Signal-only by contract: it never blocks. The deterministic part is the
# trigger (it fires on every Stop with a diff); the semantic judgment is the
# audit-grounding skill, reviewed via /octopus:review-proposals.
#
# Read-only on the project tree: never edits CLAUDE.md, docs, or the diff.

set -euo pipefail

# Project root: prefer git toplevel, fall back to cwd.
project_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Soft-skip outside a git repo — nothing to diff against.
git -C "$project_root" rev-parse --git-dir >/dev/null 2>&1 || exit 0

# Collect the working diff (staged + unstaged). Soft-skip when clean.
changed_files=$(git -C "$project_root" diff --name-only HEAD 2>/dev/null || true)
[[ -z "$changed_files" ]] && exit 0

file_count=$(printf '%s\n' "$changed_files" | grep -c . || true)

proposals_dir="$project_root/.octopus/proposals"
mkdir -p "$proposals_dir"

timestamp=$(date +%Y-%m-%d-%H%M%S)
proposal_file="$proposals_dir/$timestamp-grounding.md"

{
  echo "# Grounding review requested"
  echo ""
  echo "- **Date:** $(date -Iseconds)"
  echo "- **Project:** $(basename "$project_root")"
  echo "- **Changed files:** $file_count"
  echo ""
  echo "Auto-generated by \`hooks/stop/grounding-check.sh\` (RM-088)."
  echo "An agent task ended with an uncommitted diff. Run the"
  echo "\`audit-grounding\` skill against this diff to surface semantic"
  echo "hallucination before the change is committed or merged:"
  echo ""
  echo "- **invented-convention** — naming/folder/field/structure not"
  echo "  grounded in \`CONTEXT.md\` or an ADR."
  echo "- **unsupported-domain-fact** — a domain claim that contradicts or"
  echo "  is absent from \`docs/adr/\` and \`knowledge/\`."
  echo ""
  echo "This is a **signal only** — review and decide; nothing is blocked."
  echo ""
  echo "## Changed files"
  echo ""
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    echo "- \`$f\`"
  done <<<"$changed_files"
  echo ""
  echo "## Next step"
  echo ""
  echo "Run \`audit-grounding\` against the diff, then review with"
  echo "\`/octopus:review-proposals\`. Promote real divergences; archive the rest."
} > "$proposal_file"

echo "Octopus: grounding review queued at $proposal_file ($file_count file(s))" >&2
exit 0
