#!/usr/bin/env bash
# RM-086 — Stop hook that scans the session transcript for signals worth
# preserving (user corrections, agent re-discoveries) and writes a
# proposal to .octopus/proposals/<timestamp>.md for manual review.
#
# Read-only on the project tree: never edits CLAUDE.md or knowledge/.
# Manual review via /octopus:review-proposals.

set -euo pipefail

# Stop hook receives JSON on stdin with transcript_path.
input=$(cat)
transcript_path=$(jq -r '.transcript_path // empty' <<<"$input" 2>/dev/null || true)

# Soft-skip when transcript not available (older Claude Code, other agent).
[[ -z "$transcript_path" || ! -f "$transcript_path" ]] && exit 0

# Soft-skip when jq isn't available (degraded environments).
command -v jq >/dev/null 2>&1 || exit 0

# Project root: prefer cwd, fall back to git toplevel.
project_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
proposals_dir="$project_root/.octopus/proposals"
mkdir -p "$proposals_dir"

# --- Heuristics ----------------------------------------------------------

# Signal 1 — User corrections. Strict pattern: messages starting with a
# correction marker. Reduces false positives vs. matching anywhere.
correction_pattern='^(no[,. ]|nao[,. ]|não[,. ]|don'\''t |dont |stop |wrong|incorrect|actually|instead|remove |delete |that'\''s wrong|isso .*errad)'

corrections=$(jq -r --arg pat "$correction_pattern" '
  select(.type == "user") |
  .message.content |
  if type == "string" then . else "" end |
  select(test($pat; "i")) |
  .[0:200]
' "$transcript_path" 2>/dev/null | head -10)

correction_count=$(echo "$corrections" | grep -c . || true)

# Signal 2 — Re-discoveries. Same Read file_path 3+ times, or same Grep
# pattern 3+ times. Threshold of 3 reduces noise vs. normal edit cycles.
rereads=$(jq -r '
  select(.type == "assistant") |
  .message.content[]? |
  select(.type == "tool_use") |
  select(.name == "Read") |
  .input.file_path // empty
' "$transcript_path" 2>/dev/null | sort | uniq -c | awk '$1 >= 3 {print $1 "× " $2}')

regreps=$(jq -r '
  select(.type == "assistant") |
  .message.content[]? |
  select(.type == "tool_use") |
  select(.name == "Grep") |
  .input.pattern // empty
' "$transcript_path" 2>/dev/null | sort | uniq -c | awk '$1 >= 3 {print $1 "× " $2}')

reread_count=$(echo "$rereads" | grep -c . || true)
regrep_count=$(echo "$regreps" | grep -c . || true)

# --- Exit early when no signal worth reporting --------------------------

total=$((correction_count + reread_count + regrep_count))
[[ $total -eq 0 ]] && exit 0

# --- Write proposal -----------------------------------------------------

timestamp=$(date +%Y-%m-%d-%H%M%S)
session_id=$(basename "$transcript_path" .jsonl)
proposal_file="$proposals_dir/$timestamp.md"

{
  echo "# Session knowledge proposal"
  echo ""
  echo "- **Date:** $(date -Iseconds)"
  echo "- **Session:** $session_id"
  echo "- **Project:** $(basename "$project_root")"
  echo ""
  echo "Auto-generated by \`hooks/stop/propose-knowledge-update.sh\` (RM-086)."
  echo "Review with \`/octopus:review-proposals\` and promote actionable"
  echo "items to \`knowledge/\`, \`CLAUDE.md\`, or \`rules/\` as appropriate."
  echo ""

  if [[ $correction_count -gt 0 ]]; then
    echo "## Corrections observed ($correction_count)"
    echo ""
    echo "User messages that started with a correction marker. The pattern"
    echo "behind each correction may be worth a rule or knowledge entry."
    echo ""
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "- \`$line\`"
    done <<<"$corrections"
    echo ""
  fi

  if [[ $reread_count -gt 0 ]]; then
    echo "## Re-reads observed ($reread_count)"
    echo ""
    echo "Files read 3 or more times in this session. Consider pinning the"
    echo "relevant context in \`CLAUDE.md\` or \`knowledge/\` so the next"
    echo "session does not re-discover them."
    echo ""
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "- $line"
    done <<<"$rereads"
    echo ""
  fi

  if [[ $regrep_count -gt 0 ]]; then
    echo "## Re-greps observed ($regrep_count)"
    echo ""
    echo "Patterns grep'd 3 or more times. Recurring searches usually mean"
    echo "the answer belongs in the project's domain glossary (\`CONTEXT.md\`)"
    echo "or in a skill description that surfaces the location."
    echo ""
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      echo "- $line"
    done <<<"$regreps"
    echo ""
  fi

  echo "## Next step"
  echo ""
  echo "Review this file with \`/octopus:review-proposals\`. Promote actionable"
  echo "findings; archive or delete the rest."
} > "$proposal_file"

echo "Octopus: session proposal written to $proposal_file" >&2
exit 0
