#!/usr/bin/env bash
# RM-111 — Stop hook that, at task end on a code diff, queues a verification
# review: it writes a proposal to .octopus/proposals/<timestamp>-verification.md
# asking for an `audit-verification` run, when the work looks unverified (no
# build/test/typecheck ran this session, or the diff adds a missing-file
# reference).
#
# Signal-only by contract: it never blocks and NEVER invokes an LLM. The
# deterministic part is the trigger; the `unverified-completion-claim` judgment
# is the audit-verification skill, run on demand via /octopus:review-proposals.
#
# Read-only on the project tree except .octopus/proposals/ (gitignored).

set -euo pipefail

# Stop hook receives JSON on stdin with transcript_path (optional — the
# run-evidence scan degrades without it; see RM-111 spec).
input=$(cat 2>/dev/null || true)
transcript_path=$(printf '%s' "$input" | jq -r '.transcript_path // empty' 2>/dev/null || true)

# Only meaningful inside a git repo. Soft-skip otherwise.
project_root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

# Code-diff gate: skip a clean tree and docs-only changes — a docs change is
# not "unverified work".
changed=$(git -C "$project_root" diff --name-only HEAD 2>/dev/null || true)
[[ -z "$changed" ]] && exit 0
code_changed=$(grep -vE '\.(md|mdx|txt|rst)$|^docs/' <<<"$changed" || true)
[[ -z "$code_changed" ]] && exit 0

# unresolved-reference (deterministic, zero LLM): a changed code file whose
# relative import names a file path that does not resolve on disk — what the
# build would reject. Reliable + language-agnostic for the missing-file case.
vc_resolve_exists() {  # importing-file relpath
  local base p cand
  base="$(dirname "$1")"; p="$base/$2"
  for cand in "$p" "$p.ts" "$p.tsx" "$p.js" "$p.jsx" "$p.mjs" "$p/index.ts" "$p/index.js"; do
    [[ -e "$cand" ]] && return 0
  done
  return 1
}
unresolved=""
while IFS= read -r f; do
  [[ -n "$f" && -f "$project_root/$f" ]] || continue
  while IFS= read -r rel; do
    [[ -n "$rel" ]] || continue
    vc_resolve_exists "$project_root/$f" "$rel" || unresolved+="$f → $rel"$'\n'
  done < <(grep -oE "['\"]\.\.?/[^'\"]+['\"]" "$project_root/$f" 2>/dev/null \
             | tr -d "'\"" | sort -u)
done <<<"$code_changed"

# Run-evidence scan (deterministic, zero LLM): did a build / test / typecheck
# run this session? A match means the work was verified. No transcript ⇒ cannot
# confirm ⇒ treat as unverified (degrade to queue, per spec Risks).
run_re='tsc|mypy|ruff|pytest|jest|vitest|dotnet (build|test)|go (test|build)|cargo (test|build)|(npm|yarn|pnpm)( run)? (test|build|typecheck)|gradle|mvn (test|verify)'
ran=0
if [[ -n "$transcript_path" && -f "$transcript_path" ]] \
   && grep -qE "$run_re" "$transcript_path" 2>/dev/null; then
  ran=1
fi

# Suppress only when the work ran AND nothing references a missing file.
[[ "$ran" == 1 && -z "$unresolved" ]] && exit 0

proposals_dir="$project_root/.octopus/proposals"
mkdir -p "$proposals_dir"
timestamp=$(date +%Y-%m-%d-%H%M%S)
proposal_file="$proposals_dir/$timestamp-verification.md"
code_count=$(printf '%s\n' "$code_changed" | grep -c . || true)

{
  echo "# Verification review requested"
  echo ""
  echo "- **Date:** $(date -Iseconds)"
  echo "- **Project:** $(basename "$project_root")"
  echo "- **Changed code files:** $code_count"
  echo ""
  echo "Auto-generated by \`hooks/stop/verification-check.sh\` (RM-111)."
  echo "An agent task ended with an uncommitted code diff. Run the"
  echo "\`audit-verification\` skill against this diff + session to surface:"
  echo ""
  echo "- **unverified-completion-claim** — the session asserts done / passing"
  echo "  / fixed, but no build/test/typecheck ran to support it."
  echo "- **unresolved-reference** — the diff adds a reference the build rejects."
  echo ""
  echo "This is a **signal only** — review and decide; nothing is blocked."
  echo ""
  echo "- **Run detected this session:** $([[ "$ran" == 1 ]] && echo yes || echo "no — completion claim unverified")"
  echo ""
  if [[ -n "$unresolved" ]]; then
    echo "## unresolved-reference (deterministic)"
    echo ""
    echo "These changed files import a relative path that does not resolve on disk —"
    echo "the build would reject them:"
    echo ""
    while IFS= read -r u; do [[ -z "$u" ]] && continue; echo "- $u"; done <<<"$unresolved"
    echo ""
  fi
  echo "## Changed code files"
  echo ""
  while IFS= read -r f; do [[ -z "$f" ]] && continue; echo "- \`$f\`"; done <<<"$code_changed"
  echo ""
  echo "## Next step"
  echo ""
  echo "Run \`audit-verification\` (cheap tier) against the diff, then review with"
  echo "\`/octopus:review-proposals\`. Promote real gaps; archive the rest."
} > "$proposal_file"

echo "Octopus: verification review queued at $proposal_file ($code_count code file(s))" >&2
exit 0
